# Riot API
API_KEY = ''
REGION = 'EUW1'
REGION_DATA_DRAGON = 'euw'

TEAM_ID_BLUE = 100
TEAM_ID_RED = 200

# Google sheets API
TEAM_SHEET_ID = '1pDJt_9D4lv-p39ljnH2ClDlAlCd6d7LD85qVPZB0e0Y'

# Team sheet constants
RESULT_WIN = 'W'
RESULT_LOSE = 'L'

WORKSHEET_GAME_STATS = 'Game Stats'
ROLE_WORKSHEETS = {
    0: 'Top Lane',
    1: 'Jungle',
    2: 'Mid Lane',
    3: 'Bottom',
    4: 'Support'
}

ROLE_FLEX_INDEX = {
    0: 2,
    1: 1,
    2: 4,
    3: 3,
    4: 0
}

FLEX_QUEUE_ID = 440;

GAME_STAT_STARTING_ROW = 2
COL_GAME_STAT_DATE = 'B'
COL_GAME_STAT_GAME_TIME_FORMATTED = 'E'
COL_GAME_STAT_GAME_TIME = 'F'
COL_GAME_STAT_RESULT = 'G'
COL_GAME_STAT_SIDE = 'H'
COL_GAME_STAT_MATCH_ID = 'K'

COL_PLAYER_STAT_CHAMPION_NAME = 'D'
COL_PLAYER_STAT_KILLS = 'E'
COL_PLAYER_STAT_DEATHS = 'F'
COL_PLAYER_STAT_ASSISTS = 'G'
COL_PLAYER_STAT_DMG_TO_CHAMPS = 'J'
COL_PLAYER_STAT_DMG_TAKEN = 'L'
COL_PLAYER_STAT_WARDS_PLACED = 'M'
COL_PLAYER_STAT_WARDS_DESTROYED = 'N'
COL_PLAYER_STAT_WARDS_BOUGHT = 'O'
COL_PLAYER_STAT_VISION_SCORE = 'P'
COL_PLAYER_STAT_CREEP_SCORE = 'V'
COL_PLAYER_STAT_GOLD_EARNED = 'X'
