# Google sheets
TEAM_SHEET_ID = ''  # INSERT SOMETHING HERE


# Riot API
API_KEY = 'RGAPI-34613668-6735-4d6e-9e29-d73258efddc3'
REGION = 'EUW1'
REGION_DATA_DRAGON = 'euw'

TEAM_ID_BLUE = 100
TEAM_ID_RED = 200

# Team sheet constants
RESULT_WIN = 'W'
RESULT_LOSE = 'L'

WORKSHEET_GAME_STATS = 'Game Stats'
ROLE_WORKSHEETS = {
    0: 'Top Lane',
    1: 'Jungle',
    2: 'Mid Lane',
    3: 'Bottom',
    4: 'Support'
}

GAME_STAT_STARTING_ROW = 2
COL_GAME_STAT_DATE = 'B'
COL_GAME_STAT_GAME_TIME_FORMATTED = 'E'
COL_GAME_STAT_GAME_TIME = 'F'
COL_GAME_STAT_RESULT = 'G'
COL_GAME_STAT_SIDE = 'H'
COL_GAME_STAT_MATCH_ID = 'J'
COL_GAME_STAT_TOP_INDEX = 'K'
COL_GAME_STAT_JGL_INDEX = 'L'
COL_GAME_STAT_MID_INDEX = 'M'
COL_GAME_STAT_ADC_INDEX = 'N'
COL_GAME_STAT_SUP_INDEX = 'O'
COL_GAME_STAT_LAST_COL = 'O'

COL_PLAYER_STAT_CHAMPION_NAME = 'D'
COL_PLAYER_STAT_KILLS = 'E'
COL_PLAYER_STAT_DEATHS = 'F'
COL_PLAYER_STAT_ASSISTS = 'G'
COL_PLAYER_STAT_DMG_TO_CHAMPS = 'J'
COL_PLAYER_STAT_DMG_TAKEN = 'L'
COL_PLAYER_STAT_WARDS_PLACED = 'M'
COL_PLAYER_STAT_WARDS_DESTROYED = 'N'
COL_PLAYER_STAT_WARDS_BOUGHT = 'O'
COL_PLAYER_STAT_VISION_SCORE = 'P'
COL_PLAYER_STAT_CREEP_SCORE = 'T'
COL_PLAYER_STAT_GOLD_EARNED = 'V'