# Riot API
API_KEY = 'RGAPI-4e618cd2-84f4-4211-b4b1-c098891528a9'
REGION = 'EUW1'
TEAM_ID_BLUE = 100
TEAM_ID_RED = 200

# Google sheets API
TEAM_SHEET_ID = '1pDJt_9D4lv-p39ljnH2ClDlAlCd6d7LD85qVPZB0e0Y'

# Team sheet constants
RESULT_WIN = 'W'
RESULT_LOSE = 'L'

WORKSHEET_GAME_STATS = 'Game Stats'

GAME_STAT_STARTING_ROW = 2
GAME_STAT_DATE_COL = 'B'
GAME_STAT_GAME_TIME_FORMATTED_COL = 'E'
GAME_STAT_GAME_TIME_COL = 'F'
GAME_STAT_RESULT_COL = 'G'
GAME_STAT_SIDE_COL = 'H'
GAME_STAT_MATCH_ID_COL = 'K'
